/**
 * Spec stage — generates a detailed feature specification markdown document.
 * This is a human-in-the-loop checkpoint by default.
 */

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import {
  createSpec,
  saveSpec,
  addProgressEntry,
  updateSpecStatus,
  type SpecTask,
} from '../../tracker/spec.js';
import { createProvider } from '../../llm/factory.js';
import { withRetry } from '../../utils/retry.js';
import { loadConfig } from '../../config/loader.js';
import { getLogger } from '../../logger/index.js';
import type { PipelineState } from '../state.js';

const log = getLogger('spec');

export async function runSpecStage(state: PipelineState): Promise<void> {
  const cfg = loadConfig();
  const provider = createProvider();

  const promptPath = join(process.cwd(), 'prompts', 'spec.md');
  const promptTemplate = existsSync(promptPath)
    ? readFileSync(promptPath, 'utf-8')
    : DEFAULT_SPEC_PROMPT;

  const systemPrompt = promptTemplate
    .replace('{{FEATURE_DESCRIPTION}}', state.featureDescription)
    .replace('{{SIMILAR_PATTERNS}}', state.similarPatterns ?? 'No prior analysis available.');

  log.info('Generating feature specification...');

  const response = await withRetry(
    () =>
      provider.complete(
        [
          {
            role: 'user',
            content: `Generate a complete specification for: ${state.featureDescription}`,
          },
        ],
        {
          systemPrompt,
          maxTokens: cfg.llm.maxTokens,
          temperature: cfg.llm.temperature,
        }
      ),
    {
      maxAttempts: cfg.pipeline.maxRetries,
      onRetry: (attempt, err, delay) =>
        log.warn({ attempt, delay }, 'Retrying spec LLM call'),
    }
  );

  const parsed = parseSpecResponse(response.content);

  // Create or update spec document
  const spec = createSpec(state.featureDescription, parsed.goal);
  spec.approach = parsed.approach;
  spec.tasks = parsed.tasks;
  spec.implementationNotes = parsed.implementationNotes;

  updateSpecStatus(spec, 'in-progress');
  addProgressEntry(spec, 'spec', 'Specification generated by AI. Awaiting review.');
  saveSpec(spec);

  state.spec = spec;
  state.specFilePath = spec.filePath;

  log.info({ specFile: spec.filePath }, 'Spec saved');
  log.info(
    {
      tokens: response.usage.totalTokens,
      cost: response.usage.estimatedCostUsd?.toFixed(4),
    },
    'Spec stage complete'
  );
}

interface ParsedSpec {
  goal: string;
  approach: string;
  tasks: SpecTask[];
  implementationNotes: string;
}

function parseSpecResponse(content: string): ParsedSpec {
  const extractSection = (name: string): string => {
    const regex = new RegExp(`## ${name}\\n\\n([\\s\\S]*?)(?=\\n## |$)`);
    return content.match(regex)?.[1]?.trim() ?? '';
  };

  const parseTasks = (raw: string): SpecTask[] => {
    return raw
      .split('\n')
      .filter((l) => l.trim().startsWith('-'))
      .map((line, i) => ({
        id: `task-${i + 1}`,
        description: line.replace(/^-\s*/, '').trim(),
        status: 'pending' as const,
      }));
  };

  return {
    goal: extractSection('Goal') || extractSection('Overview') || content.slice(0, 500),
    approach: extractSection('Approach') || extractSection('Design'),
    tasks: parseTasks(extractSection('Tasks') || extractSection('Implementation Plan')),
    implementationNotes: extractSection('Notes') || extractSection('Implementation Notes'),
  };
}

const DEFAULT_SPEC_PROMPT = `You are a senior software engineer writing a detailed feature specification.

## Feature Request
{{FEATURE_DESCRIPTION}}

## Codebase Analysis
{{SIMILAR_PATTERNS}}

## Instructions
Write a comprehensive specification for this feature. The spec will be saved as a markdown document and used to guide implementation.

## Required Output Format

## Goal

[Clear, one-paragraph description of what this feature does and why it's needed]

## Approach

[Technical approach: architecture decisions, data flow, key design choices. Reference existing code where relevant.]

## Tasks

- [First concrete implementation task]
- [Second task]
- [Continue for all tasks needed]

## Implementation Notes

[Important technical details, edge cases, constraints, and gotchas the implementer should know]

## Acceptance Criteria

- [Measurable criterion 1]
- [Measurable criterion 2]
`;
