import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';

const CONFIG_TEMPLATE = `# SkillBender configuration
# Generated by: skillbender init

version: "1"

llm:
  provider: anthropic          # anthropic | openai | ollama
  model: claude-sonnet-4-6
  maxTokens: 8192
  temperature: 0.2

pipeline:
  stages:
    - analyze
    - spec
    - implement
    - validate
    - document
  checkpoints:
    - spec
  maxRetries: 3

analyzer:
  include:
    - src
  exclude:
    - node_modules
    - dist

tracker:
  outputDir: .skillbender/specs
  autoCommit: false

docs:
  dirs:
    - docs
    - README.md
  createIfMissing: true

logging:
  level: info
  format: pretty
`;

const GITIGNORE_ADDITIONS = `
# SkillBender
.skillbender/specs/
`;

export async function runInitCommand(): Promise<void> {
  const cwd = process.cwd();
  const configDir = join(cwd, '.skillbender');
  const configFile = join(configDir, 'config.yaml');
  const specsDir = join(configDir, 'specs');

  if (existsSync(configFile)) {
    console.log(chalk.yellow('SkillBender is already initialized (.skillbender/config.yaml exists).'));
    return;
  }

  mkdirSync(configDir, { recursive: true });
  mkdirSync(specsDir, { recursive: true });
  writeFileSync(configFile, CONFIG_TEMPLATE, 'utf-8');

  // Add specs dir to .gitignore (keep config, ignore generated specs)
  const gitignorePath = join(cwd, '.gitignore');
  if (existsSync(gitignorePath)) {
    const existing = readFileSync(gitignorePath, 'utf-8');
    if (!existing.includes('.skillbender/specs/')) {
      writeFileSync(gitignorePath, existing.trimEnd() + GITIGNORE_ADDITIONS, 'utf-8');
    }
  }

  console.log(chalk.green('\n✓ SkillBender initialized!\n'));
  console.log('  Created:');
  console.log(chalk.cyan('    .skillbender/config.yaml') + '  — project configuration');
  console.log(chalk.cyan('    .skillbender/specs/') + '         — feature spec storage');
  console.log('');
  console.log('  Next steps:');
  console.log('    1. Set your API key:  ' + chalk.cyan('export ANTHROPIC_API_KEY=sk-...'));
  console.log('    2. Resolve a feature: ' + chalk.cyan('skillbender resolve "Add user auth"'));
  console.log('');
}
